#!/usr/bin/env bash
# =============================================================================
# setup_openwebui.sh — Install Open WebUI in a Python virtual environment
#
# What this script does:
#   • Ensures Python 3.11+ is available (via Homebrew if needed)
#   • Creates an isolated venv at ~/.local/openwebui-venv
#   • Installs the `open-webui` pip package
#   • Copies the launchd plist so Open WebUI starts on login
#   • Starts the Open WebUI server on 127.0.0.1:3000
#
# Motivation:
#   Open WebUI is the most polished self-hosted interface for Ollama.  It ships
#   with user management, API-key generation, model switching, and a chat history
#   — all without requiring Docker.  Running it in a venv keeps system Python
#   clean and makes upgrades trivial (`pip install -U open-webui`).
#
#   WEBUI_SECRET_KEY is generated once and stored in ~/.local/openwebui.env so
#   that session cookies survive restarts.  This file is NOT committed to git.
# =============================================================================

set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
LAUNCHAGENTS_DIR="${HOME}/Library/LaunchAgents"
PLIST_SRC="${REPO_DIR}/config/openwebui.plist"
PLIST_DST="${LAUNCHAGENTS_DIR}/com.openwebui.server.plist"
VENV_DIR="${HOME}/.local/openwebui-venv"
ENV_FILE="${HOME}/.local/openwebui.env"
LOG_DIR="${HOME}/Library/Logs"

# ── 1. Python 3.11+ ────────────────────────────────────────────────────────
PYTHON_BIN=""
for candidate in python3.13 python3.12 python3.11 python3; do
  if command -v "${candidate}" &>/dev/null; then
    VER=$("${candidate}" -c "import sys; print(sys.version_info >= (3,11))" 2>/dev/null)
    if [[ "${VER}" == "True" ]]; then
      PYTHON_BIN="${candidate}"
      break
    fi
  fi
done

if [[ -z "${PYTHON_BIN}" ]]; then
  echo "  Python 3.11+ not found — installing via Homebrew …"
  if ! command -v brew &>/dev/null; then
    eval "$(/opt/homebrew/bin/brew shellenv)"
  fi
  brew install python@3.11
  PYTHON_BIN="$(brew --prefix python@3.11)/bin/python3.11"
fi

echo "  Using Python: ${PYTHON_BIN} ($(${PYTHON_BIN} --version))"

# ── 2. Virtual environment ─────────────────────────────────────────────────
if [[ ! -d "${VENV_DIR}" ]]; then
  echo "  Creating virtual environment at ${VENV_DIR} …"
  "${PYTHON_BIN}" -m venv "${VENV_DIR}"
fi

# shellcheck source=/dev/null
source "${VENV_DIR}/bin/activate"

# ── 3. Install / upgrade Open WebUI ────────────────────────────────────────
echo "  Installing / upgrading open-webui …"
pip install --quiet --upgrade pip
pip install --quiet open-webui

# ── 4. Generate secret key (once) ──────────────────────────────────────────
mkdir -p "$(dirname "${ENV_FILE}")"
if [[ ! -f "${ENV_FILE}" ]]; then
  echo "  Generating WEBUI_SECRET_KEY …"
  SECRET=$(python3 -c "import secrets; print(secrets.token_hex(32))")
  cat > "${ENV_FILE}" <<EOF
# Open WebUI environment — auto-generated by setup_openwebui.sh
# Do NOT commit this file.
WEBUI_SECRET_KEY=${SECRET}
OLLAMA_BASE_URL=http://127.0.0.1:11434
WEBUI_AUTH=True
EOF
  chmod 600 "${ENV_FILE}"
  echo "  Secret key written to ${ENV_FILE}"
else
  echo "  ${ENV_FILE} already exists — keeping existing secret key."
fi

# ── 5. launchd plist ───────────────────────────────────────────────────────
mkdir -p "${LAUNCHAGENTS_DIR}" "${LOG_DIR}"

if [[ -f "${PLIST_DST}" ]]; then
  echo "  Unloading existing Open WebUI launchd agent …"
  launchctl unload "${PLIST_DST}" 2>/dev/null || true
fi

echo "  Installing Open WebUI launchd plist …"
# Substitute the actual venv path into the plist before copying
sed "s|__VENV_DIR__|${VENV_DIR}|g; s|__HOME__|${HOME}|g" \
  "${PLIST_SRC}" > "${PLIST_DST}"
launchctl load -w "${PLIST_DST}"

# ── 6. Wait for server ─────────────────────────────────────────────────────
echo "  Waiting for Open WebUI to start (may take up to 30 s) …"
for i in {1..15}; do
  if curl -sf http://127.0.0.1:3000 &>/dev/null; then
    echo "  Open WebUI is up."
    break
  fi
  sleep 2
done

if ! curl -sf http://127.0.0.1:3000 &>/dev/null; then
  echo "  ⚠  Open WebUI did not respond — check ~/Library/Logs/openwebui.log"
  exit 1
fi

echo "  ✓ Open WebUI setup complete."
echo "    URL : http://127.0.0.1:3000"
echo "    On first visit, create an admin account."
